export const LocalizedStrings = {
  "en": {
    patients: "Patients",
    PATIENTS: "< PATIENTS",
    welcome: "Welcome Back",
    dob: "Date of Birth",
    DOB: "DOB",
    sex: "Sex",
    gender: "Gender",
    GENDER: "GENDER",
    patientSummary: "Patient Summary",
    noContent: "No content yet",
    age: "age",
    edit: "EDIT",
    back: "< BACK",
    save: "SAVE",
    confirm: "CONFIRM",
    cancel: "CANCEL",
    yes: "Yes",
    no: "No",
    firstName: "First Name",
    surname: "Surname",
    country: "Country",
    hometown: "Hometown",
    selectDob: "Select DOB",
    phone: "Phone",
    patientSearch: "Search patient name...",
    search: "Search",
    minAge: "Min Age",
    maxAge: "Max Age",
    advancedFilters: "Advanced Filters ▼",
    hideFilters: "Hide Filters",
    clearFilters: "Clear All Filters",
    newPatient: "New Patient",
    newVisit: "New Visit",
    newEntry: "New Entry",
    camp: "Camp",
    vitals: "Vitals",
    examination: "Examination",
    notes: "Notes",
    complaint: "Complaint",
    treatment: "Treatment",
    diagnosis: "Diagnosis",
    medicineDispensed: "Medicine Dispensed",
    prescriptions: "Prescriptions",
    allergies: "Allergies",
    medicalHistory: "Medical History",
    covidScreening: "COVID-19 Screening",
    enterTextHere: "Enter text here.",
    visitDate: "Visit Date",
    visitHistory: "Visit History",
    visitEvents: "Visit Events",
    visitType: "Visit Type",
    trends: "TRENDS",
    eventType: "Event Type",
    datePrescribed: "Date Prescibed",
    provider: "Provider",
    severity: "Severity",
    onsetDate: "Onset Date",
    departure: "Departure",
    to: "to",
    return: "Return",
    fever: "Fever or Chills?",
    dryCough: "Dry Cough?",
    diffBreathing: "Difficulty Breathing?",
    soreThroat: "Sore Throat or Runny Nose?",
    nausea: "Nausea, vomiting, or diarrhea?",
    chestPain: "Chest Pain?",
    confusion: "New Confusion?",
    bluish: "Bluish Lips or Face?",
    fatigue: "Fatigue?",
    aches: "Aches and Pains?",
    headache: "Headache?",
    changeTasteSmell: "Change of Taste or Smell?",
    diabetes: "Diabetes?",
    cardioDisease: "Cardiovascular Disease?",
    pulmonaryDisease: "Pulmonary Disease?",
    renalDisease: "Renal Disease?",
    malignancy: "Malignancy?",
    pregnant: "Pregnant or 2 weeks postpartum?",
    immunocompromised: "Immunocompromised?",
    exposureKnown: "Recent contact with individuals with known or suspected COVID-19?",
    travel: "Recent travel out of the country?",
    symptomsDate: "Onset Date of first symptoms?",
    riskFactors: "Risk Factors",
    hideRiskFactors: "Hide Risk Factors",
    testIsolate: "Test/Isolate Patient",
    seekCare: "Seek Emergency Care and Isolate",
    noAction: "No Action Necessary",
    syncFailure: "Database Sync Failure!",
    syncFailureConnection: "Check internet connection",
    syncFailureSystem: "Contact system administrator",
    syncSuccess: "Database Sync Success",
    surgeryHx: "Previous Surgeries",
    chronicConditions: "Chronic Conditions",
    currentMedications: "Current Medications",
    vaccinations: "Vaccinations",
    generalObservations: "General Observations",
    covid19: "COVID-19",
    referral: "Referral to Specialist",
    medicine: "Medicine",
    medication: "Medication",
    type: "Type",
    tablet: "Tablet",
    syrup: "Syrup",
    ampule: "Ampule",
    suppository: "Suppository",
    cream: "Cream",
    drops: "Drops",
    bottle: "Bottle",
    spray: "Spray",
    gel: "Gel",
    lotion: "Lotion",
    dosage: "Dosage",
    days: "Days",
    dentalTreatment: "Dental Treatment",
    physiotherapy: "Physiotherapy",
    previousTreatment: "Previous Physio Treatment",
    findings: "Examination Findings",
    treatmentPlan: "Treatment Plan",
    treatmentSession: "Treatment Session",
    recommendations: "Recommendations",
    patientSnapshot: "Patient Snapshot",
    logOut: "Log Out",
    sync: "Sync",
    adult: "Adult",
    pediatric: "Pediatric",
    
    // PathologicalHistory
    pathologicalHistory: "Adult Pathological personal history",
    childhoodDiseases: "Infectious diseases of childhood",
    cardiovascular: "Cardiovascular",
    customizedAllergies: "allergies",
    pulmonary: "Pulmonary",
    chronicDiseases: "Chronic diseases",
    transfusions: "Transfusions",
    sexuallyTransmittedInfections: "Sexually Transmitted Infections",
    digestive: "Digestive",
    surgical: "Surgical",
    hospitalizations: "Hospitalizations",
    others: "Others",
    other: "Other",
    specify: "Specify",
    specifyDesc: "Here the type of history, date of diagnosis or event and treatment are well detailed",
    // Non-pathological personal history
    nonPathologicalHistory: "Adult Non-pathological personal history",
    alcoholism: "Alcoholism",
    active: "Active",
    inactive: "Inactive",
    ageOfOnset: "Age of onset",
    ageOfTermination: "Age of termination",
    frequency: "Frequency",
    amountOfIntake: "Amount of intake",
    typeOfLiquor: "Type of liquor",
    smoking: "Smoking",
    startAge: "Start Age",
    endAge: "End Age",
    cigarettesNumber: "Number of cigarettes or packs per day",
    drugs: "Drugs",
    drugType: "Type of drug",
    // Gynecological-obstetric background
    gynecologicalBackground: "Gynecological-obstetric background",
    menarche: "Menarche",
    sexualLifeBeginning: "Beginning of active sexual life",
    sexualPartnersNum: "Number of sexual partners",
    familyPlanning: "Family planning",
    lastMenstrualPeriodDate: "Date of last menstrual period",
    currentPregnancy: "Current pregnancy",
    weeksOfAmenorrhea: "Weeks of amenorrhea",
    estimatedDueDate: "Estimated due date",
    lastDeliveryDate: "Date of last delivery",
    pregnanciesNumber: "Number of pregnancies",
    births: "Births",
    caesareanSection: "Caesarean section",
    abortions: "abortions",
    curettage: "Curettage",
    // Family Pathological History
    familyPathologicalHistory: "Family Pathological History",
    arterialHypertension: "Arterial hypertension",
    diabetesMellitus: "Diabetes Mellitus",
    tuberculosis: "Tuberculosis",
    cancer: "Cancer",
    epilepsy: "Epilepsy",
    heartDiseases: "Heart diseases",
    nephropathies: "Nephropathies",
    liverDiseases: "Liver diseases",
    mentalDiseases: "Mental diseases",
    familySpecifyDesc: "Here the type of history, date of diagnosis or event and degree of consanguinity of the relative is well detailed",
    // Socioeconomic situation
    socioeconomicSituation: "Socioeconomic situation",
    house: "House",
    own: "own",
    rented: "rented",
    walls: "Walls",
    plastic: "Plastic",
    boards: "Boards",
    block: "Block",
    miniSkirt: "Mini skirt",
    zinc: "Zinc",
    flat: "Flat",
    land: "Land",
    tiling: "Tiling",
    ceramics: "Ceramics",
    ceiling: "Ceiling",
    roofTile: "Roof tile",
    bedrooms: "Bedrooms",
    animals: "Animals",
    pet: "Pet",
    farm: "Farm",
    specifyOnesQuantity: "Specify which ones and quantity",
    waterSource: "Water source",
    well: "Well",
    potable: "Potable",
    electricPower: "Electric power",
    toilet: "Toilet",
    latrine: "Latrine",
    kitchen: "Kitchen",
    gas: "Gas",
    firewood: "Firewood",
    population: "Population",
    children_0_5: "Children (0 to 5 years)",
    children_6_10: "Children (6 to 10 years)",
    children_11_15: "Children (11 to 15 years)",
    adults: "Adults",
    seniors: "Seniors",
    women: "Women",
    men: "Men",
    peopleWorkingNumber: "Number of people in the family that work",
    // Physical exploration
    physicalExploration: "Physical exploration",
    vitalSigns: "Vital Signs",
    bloodPressure: "Blood Pressure",
    heartRate: "Heart Rate",
    respiratoryRate: "Respiratory Rate",
    temperature: "Temperature",
    oxygenSaturation: "Oxygen Saturation",
    weight: "Weight",
    height: "Height",
    bodyMassIndex: "Body Mass Index",
    consultationReason: "Reason for consultation",
    illnessHistory: "History of current illness",
    objective: "Objective",
    head: "Head",
    eyes: "Eyes",
    earsNoseMouth: "Ears, nose and mouth",
    neck: "Neck",
    chest: "Chest",
    heart: "Heart",
    lungFields: "Lung Fields",
    abdomen: "Abdomen",
    genitals: "Genitals",
    skeletalMuscle: "Skeletal muscle",
    extremities: "Extremities",
    neurological: "Neurological",
    evaluation: "Evaluation",
    plans: "Plans",
    feeding: "Feeding",
    medicines: "Medicines",
    exams: "Exams",
    normsOrRecommendations: "Norms or recommendations",
    treatingPhysician: "Treating Physician",
    minsaCode: "Minsa Code",
    // EMERGENCY ATTENTION SHEET
    emergencyAttentionSheet: "Emergency Attention Sheet",
    emergencyAdmission: "Emergency admission",
    dayMonthYear: "Day/month/Year",
    hour: "Hour",
    medicalRecord: "Number of medical record",
    names: "Names",
    surnames: "Surnames",
    occupation: "Occupation",
    address: "Address",
    phoneNumber: "Phone number",
    id: "ID",
    arrivesIn: "Arrives in",
    ambulance: "Ambulance",
    walking: "Walking",
    particular: "Particular",
    buses: "buses",
    accidentCauses: "Causes of accident or violence",
    motorizedVehicle: "motorized vehicle",
    naturalPhenomenon: "Natural phenomenon",
    fireExplosion: "Fire/Explosion",
    drop: "Drop",
    assaultBattery: "Assault/Battery",
    lateEffects: "late effects",
    machinery: "Machinery",
    suicideAttempt: "Suicide attempt",
    accidentPlace: "Place of accident or violence",
    work: "Work",
    sportFun: "Sport/Fun",
    livingPlace: "living place",
    publicRoad: "Public road",
    studyCenter: "study center",
    notifyTo: "In case of emergency notify to",
    name: "Name",
    relationship: "Relationship",
    telephone: "Telephone",
    breathingFrequency: "Breathing frequency",
    attentionDateHours: "Date and Hours of attention",
    attendantName: "Name of the attendant",
    personalMedicalHistory: "Personal medical history",
    reasonForConsultation: "Reason for consultation",
    clinicalSummary: "Clinical summary",
    physicalExam: "Physical exam",
    destiny: "Destiny",
    ambulatory: "Ambulatory",
    observation: "Observation",
    ranAway: "Ran away",
    requiredOutput: "required output",
    abandonment: "Abandonment",
    referred: "Referred",
    passAway: "pass away",
    emergencyType: "Type of emergency",
    medical: "medical",
    obstetricGynecology: "obstetric gynecology",
    treatingPhysicianSignature: "Signature, Seal and Code of treating physician",
    // Postnatal History
    postnatalHistory: "Postnatal history",
    apgar: "Apgar",
    weightInGrams: "Weight in grams",
    sizeInCentimeters: "Size in centimeters",
    suffocation: "Suffocation",
    roomingIn: "Rooming-in",
    hospitalization: "Hospitalization (Place/Time)",
    // Feeding
    exclusiveBreastfeeding: "Exclusive breastfeeding",
    durationOfExclusiveBreastfeeding: "Duration of exclusive breastfeeding",
    mixedBreastfeeding: "Mixed breastfeeding",
    mixedBreastfeedingDuration: "Mixed breastfeeding duration",
    ablactation: "Ablactation",

    // Immunizations
    immunizations: "Immunizations",
    vaccines: "Vaccines",
    bcg: "BCG",
    pentavalent: "pentavalent",
    polio: "Polio",
    rotavirus: "Rotavirus",
    mmr: "MMR",
    dpt: "DPT",
    dT: "dT",
    dose1: "1 dose",
    doses2: "2 doses",
    doses3: "3 doses",
    reinforcement: "Reinforcement",
    reinforcementCount: "Reinforcement Doses Count",
    doses: "doses",

    // Psychomotor development
    psychomotorDevelopment: "Psychomotor development",
    lessThan1Month: "Less than 1 month",
    suckVigorously: "suck vigorously",
    handsClosed: "hands closed",
    flexArms: "Flex arms and legs",
    moorishReflex: "Moorish reflex",
    month1: "1 month",
    vocalize: "Vocalize",
    alternateLegMovement: "Alternate leg movement",
    openHands: "open hands",
    socialSmile: "social smile",
    months2_3: "2 – 3 months",
    lookAtMothers: "Look at the mother's face", 
    followObjects: "Follow objects with eyes",
    reactToSound: "react to sound",
    raiseHead: "raise head",
    months4_5: "4 – 5 months",
    answerToExam: "Answer to exam",
    grabObjects: "grab objects",
    makeSounds: "make sounds",
    holdsHead: "holds head",
    months6_8: "6- 8 months",
    takeToy: "Try to take a toy",
    bringsObjectsToMouth: "brings objects to mouth",
    locateSound: "locate the sound",
    turnTowardsObject: "Turn towards an object",
    months9_11: "9 – 11 months",
    playDiscover: "Play to discover",
    objectsPassed: "objects are passed",
    sitsAlone: "sits alone",
    doubleSyllables: "double syllables",
    months12_14: "12 – 14 months",
    imitateGestures: "Imitate gestures",
    topPliers: "top pliers",
    confusingWords: "confusing words",
    walkWithSupport: "walk with support",
    months15_17: "15 – 17 months",
    gesturesOnDemand: "gestures on demand",
    placeCubes: "Place cubes in container",
    sayWord: "say a word",
    walkWithoutSupport: "walk without support",
    months18_23: "18 – 23 months",
    identifyTwoObjects: "identify two objects",
    scribbles: "scribbles",
    saysThreeWords: "says three words",
    walkBackwards: "walk backwards",
    months24_35: "24 – 35 months",
    takesOffClothes: "takes off clothes",
    towerFiveCubes: "tower of five cubes",
    saysShortSentences: "says short sentences",
    kickBall: "kick ball",
    months36_59: "36 – 59 months",
    feedsItself: "feeds itself",
    saysLongSentences: "says long sentences",
    dressesAlone: "Dresses alone",
    complexOrders: "complex orders",   

    // Pediatric Pathological Personal History
    pediatricPathologicalHistory: "Pediatric Pathological Personal History",
    infections: "infections",
    surgeries: "Surgeries",

    // PediatricPhysicalExam
    pediatricPhysicalExam: "Pediatric Physical Exam",
    silvermanAnderson: "Silverman Anderson",
    sizeLength: "Size/ Length",
    anthropometricData: "Anthropometric data",
    headCircunference: "Head circunference",
    chestCircumference: "Chest circumference",
    abdominalPerimeter: "Abdominal perimeter",
    bodySurfaceArea: "Body surface area",
    attendsNameSign: "Name and sign of person who attends",

    // SUBSEQUENT EVOLUTION NOTE
    subsequentEvolutionNote: "Subsequent Evolution Note",
    nameSurname: "Name and surname",
    community: "Community",
    proceedings: "Proceedings",
    dateTime: "Date and Time",
    male: "male",
    female: "female",
    size: "size",

    // NURSING NOTE
    nursingNote: "Nursing Note",
    note: "Note",
    nurseName: "Nurse Name",

    // Ultrasound Consultation
    ultrasoundConsultation: "Ultrasound Consultation",
    lastname: "Lastname",
    origin: "Origin",
    ultrasoundPerformed: "Ultrasound performed",
    resource: "Resource",
    date: "date",

    // Laboratory Consultation
    laboratoryConsultation: "Laboratory Consultation",
    testPerformed: "Test performed",

    // Odontology Consultation
    odontologyConsultation: "Odontology Consultation",
    procedurePerformed: "Procedure performed",
    indications: "Indications",

    // Patient Form
    medicalRecordNum: "Medical Record number",
    attentionDateTime: "Date and hour of attention",
    resourceThatAttends: "Resource that attends",
    email: "Email",
    educationalStatus: "Educational status",
    preschool: "Preschool",
    primary: "Primary",
    secondary: "Secondary",
    university: "University",
    technical: "Technical",
    knowsReadWrite: "knows how to read and write",
    illiterate: "illiterate",

    religion: "Religion",
    catholic: "catholic",
    evangelical: "evangelical",
    none: "None",
    maritalStatus: "Marital status",
    single: "Single",
    married: "Married",
    stableUnion: "stable union",
    widower: "Widower",
    divorced: "Divorced",

    motherName: "Mother's name",
    fatherName: "Father's name",
    birthHistory: "Birth history",
    deliveryPlace: "Delivery place",
    deliveryDateTime: "Date, time and duration of delivery",
    gestationalAge: "Gestational age",
    deliveryCare: "Delivery care",
    nurse: "Nurse",
    midwife: "Midwife",
    via: "Via",
    vaginal: "Vaginal",
    presentation: "Presentation",
    cephalic: "cephalic",
    podalic: "podalic",
    transverse: "transverse",
    birthingEvents: "Birthing events",

  },
  "ar": {
    patients: "المرضى",
    PATIENTS: "المرضى",
    welcome: "مرحبا بعودتك",
    dob: "تاريخ الولادة",
    DOB: "تاريخ الولادة",
    sex: "جنس",
    gender: "جنس",
    GENDER: "جنس",
    patientSummary: "ملخص المريض",
    noContent: "لا يوجد محتوى حتى الآن",
    age: "عمر",
    edit: "تعديل",
    back: "رجع",
    save: "حفظ",
    confirm: "تؤكد",
    cancel: "إلغاء",
    yes: "نعم",
    no: "لا",
    firstName: "الاسم المعطى",
    surname: "الكنية",
    country: "بلد",
    hometown: "مسقط رأس",
    selectDob: "اختر تاريخ الميلاد",
    phone: "هاتف",
    patientSearch: "البحث عن اسم المريض",
    search: "بحث",
    minAge: "الحد الإدنى للعمر",
    maxAge: "العمر الأقصى",
    advancedFilters: "مرشحات متقدمة ▼",
    hideFilters: "إخفاء المرشحات",
    clearFilters: "إعادة تعيين الفلاتر",
    newPatient: "مريض جديد",
    newVisit: "زيارة جديدة",
    newEntry: "دخول جديد",
    camp: "مخيم",
    vitals: "الأعضاء الحيوية",
    examination: "فحص",
    notes: "ملاحظات",
    complaint: "شكوى",
    treatment: "علاج او معاملة",
    diagnosis: "التشخيص",
    medicineDispensed: "الأدوية المستغلة",
    prescriptions: "وصفات",
    allergies: "الحساسية",
    medicalHistory: "تاريخ طبى",
    covidScreening: "COVID-19 فحص",
    enterTextHere: "أدخل النص هنا",
    visitDate: "موعد زيارة",
    visitHistory: "زيارة التاريخ",
    visitEvents: "زيارة الأحداث",
    visitType: "نوع الزيارة",
    trends: "اتجاهات",
    eventType: "نوع الحدث",
    datePrescribed: "التاريخ المحدد",
    provider: "طبيب",
    severity: "خطورة",
    onsetDate: "تاريخ البداية",
    departure: "مغادرة",
    to: "إلى",
    return: "إرجاع",
    fever: "حمى أم قشعريرة؟",
    dryCough: "سعال جاف؟",
    diffBreathing: "صعوبة في التنفس؟",
    soreThroat: "التهاب بالحلق أو سيلان  بالأنف؟",
    nausea: "غثيان، قيء، او إسهال؟",
    chestPain: "ألم في الصدر؟",
    confusion: "اضطراب إدراكي حديث؟",
    bluish: "الشفاه الزرقاء أم الوجه؟",
    fatigue: "إعياء؟",
    aches: "اوجاع والآم؟",
    headache: "صداع الراس؟",
    changeTasteSmell: "تغير في الطعم أو الرائحة؟",
    diabetes: "داء السكري؟",
    cardioDisease: "أمراض القلب والأوعية الدموية؟",
    pulmonaryDisease: "المرض الرئوي؟",
    renalDisease: "امراض الكلى؟",
    malignancy: "خباثة؟",
    pregnant: "حامل أو أسبوعين بعد الولادة؟",
    immunocompromised: "المنقوصي المناعة؟",
    exposureKnown: "مخالطة أفراد مصابين او مشتبهين بالإصابة بفيروس كوفيد-١٩؟",
    travel: "السفر خارج البلاد بالآونة الأخيرة؟",
    symptomsDate: "تاريخ ظهور الأعراض الأولى؟",
    riskFactors: "عوامل الخطر",
    hideRiskFactors: "إخفاء عوامل الخطر",
    testIsolate: "اختبار وعزل المريض",
    seekCare: "احصل على رعاية الطوارئ واعزل نفسك",
    noAction: "لا رد فعل",
    syncFailure: "فشل مزامنة قاعدة البيانات",
    syncFailureConnection: "تحقق من اتصال الإنترنت",
    syncFailureSystem: "اتصل بمسؤول النظام",
    syncSuccess: "نجاح مزامنة قاعدة البيانات",
    surgeryHx: "العمليات السابقة",
    chronicConditions: "الامراض المزمنة",
    currentMedications: "الأدوية الحالية",
    vaccinations: "التطعيمات ",
    generalObservations: "مراقبة عامة",
    covid19: "كوفيد-١٩",
    referral: "تحويل الى مختص",
    medicine: "طب",
    medication: "دواء",
    type: "نوع",
    tablet: "قرص",
    syrup: "شراب",
    ampule: "امبولة",
    suppository: "تحميلة",
    cream: "مرهم",
    drops: "قطرات",
    bottle: "زجاجة",
    spray: "رذاذ",
    gel: "جل",
    lotion: "غسول",
    dosage: "جرعة",
    days: "ايام",
    dentalTreatment: "العناية بالاسنان",
    physiotherapy: "العلاج الطبيعي",
    previousTreatment: "جلسات العلاج الطبيعي السابقة",
    findings: "نتائج الفحص",
    treatmentPlan: "خطة العلاج ",
    treatmentSession: "جلسة العلاج",
    recommendations: "توصيات",
    patientSnapshot: "صفحة المريض",
    logOut: "تسجيل خروج",
    sync: "مزامنة",
  },
  "sp": {
    patients: "Pacientes",
    PATIENTS: "PACIENTES",
    welcome: "Bienvenido de vuelta",
    dob: "Fecha de nacimiento ",
    DOB: "Fecha de nacimiento ",
    sex: "Sexo",
    gender: "Género",
    GENDER: "GENERO",
    patientSummary: "Resumen del paciente",
    noContent: "No hay contenido aún",
    age: "EDAD",
    edit: "EDITAR",
    back: "< Volver a atrás",
    save: "GUARDAR",
    confirm: "CONFIRMAR",
    cancel: "CANCELAR",
    yes: "Sí",
    no: "No",
    firstName: "Nombre",
    surname: "Apellido",
    country: "País",
    hometown: "Ciudad de origen",
    selectDob: "Seleccione fecha de nacimiento",
    phone: "Teléfono",
    patientSearch: "Buscar nombre del paciente...",
    search: "Buscar",
    minAge: "Edad Mínima",
    maxAge: "Edad Máxima",
    advancedFilters: "Filtros Avanzados ▼",
    hideFilters: "Ocultar Filtros",
    clearFilters: "Restablecer Filtros",
    camp: "Nombre del campo de refugiados",
    vitals: "Signos vitales",
    examination: "Examen físico",
    notes: "Notas",
    complaint: "Queja/Preocupación médica",
    treatment: "Tratamiento",
    diagnosis: "Diagnóstico",
    medicineDispensed: "Medicamento suscrito",
    prescriptions: "Recetas de medicamentos",
    allergies: "Alergias",
    medicalHistory: "Historial médico",
    covidScreening: "Prueba de COVID-19",
    enterTextHere: "Introduzca texto aquí",
    visitDate: "Fecha de la visita",
    visitHistory: "Historia de la visita",
    visitEvents: "Eventos durante la visita",
    visitType: "Tipo de visita",
    trends: "Tendencias",
    eventType: "Tipo de evento",
    datePrescribed: "Fecha de prescripción",
    provider: "Proveedor médico",
    severity: "Severidad",
    onsetDate: "Fecha de comienzo de los síntomas",
    departure: "Ida",
    to: "a ",
    return: "Vuelta",
    fever: "¿Fiebre o escalofríos?",
    dryCough: "¿Tos seca?",
    diffBreathing: "¿Dificultad al respirar?",
    soreThroat: "¿Dolor de garganta o secreción nasal?",
    nausea: "¿Náuseas, vómitos o diarrea?",
    chestPain: "¿Dolor de pecho?",
    confusion: "¿Nueva confusión?",
    bluish: "¿Labios azulados/ violetas?",
    fatigue: "¿Fatiga?",
    aches: "¿Dolores y molestias?",
    headache: "¿Dolor de cabeza?",
    changeTasteSmell: "¿Cambio de gusto u olfato?",
    diabetes: "¿Diabetes?",
    cardioDisease: "¿Problemas del corazón?",
    pulmonaryDisease: "¿Enfermedad en los pulmones?",
    renalDisease: "¿Enfermedad de los riñones?",
    malignancy: "¿Cáncer?",
    pregnant: "¿Mujer recién dada a luz?",
    immunocompromised: "¿Inmunocomprometido? / ¿Tiene las defensas bajas?",
    exposureKnown: "¿Contacto reciente con personas con COVID-19 conocido o sospechado?",
    travel: "¿Viaje reciente fuera del país?",
    symptomsDate: "¿Fecha de aparición de los primeros síntomas?",
    riskFactors: "Factores de riesgo",
    hideRiskFactors: "Ocultar factores de riesgo",
    testIsolate: "Hacerle la prueba/Aislar al paciente",
    seekCare: "Busque atención de emergencia y aísle",
    noAction: "No es necesario tomar ninguna acción",
    syncFailure: "¡Fallo de sincronización!",
    syncFailureConnection: "Verifica la conexión a internet",
    syncFailureSystem: "Comuníquese con el administrador del sistema",
    syncSuccess: "Éxito en la sincronización",
    surgeryHx: "Previous Surgeries",
    chronicConditions: "Chronic Conditions",
    currentMedications: "Current Medications",
    vaccinations: "Vaccinations",
    generalObservations: "General Observations",
    covid19: "COVID-19",
    referral: "Referral to Specialist",
    medicine: "Medicine",
    medication: "Medication",
    type: "Type",
    tablet: "Tablet",
    syrup: "Syrup",
    ampule: "Ampule",
    suppository: "Suppository",
    cream: "Cream",
    drops: "Drops",
    bottle: "Bottle",
    spray: "Spray",
    gel: "Gel",
    lotion: "Lotion",
    dosage: "Dosage",
    days: "Days",
    dentalTreatment: "Dental Treatment",
    physiotherapy: "Physiotherapy",
    previousTreatment: "Previous Physio Treatment",
    findings: "Examination Findings",
    treatmentPlan: "Treatment Plan",
    treatmentSession: "Treatment Session",
    recommendations: "Recommendations",
    patientSnapshot: "Patient Snapshot",
    logOut: "Log Out",
    sync: "Sync",
    adult: "Adulto",
    pediatric: "Pediátrica",
    // PathologicalHistory
    pathologicalHistory: "Adulto Antecedentes Personales Patológicos",
    childhoodDiseases: "Enfermedades infecciosas de la infancia",
    cardiovascular: "Cardiovasculares",
    customizedAllergies: "Alergias",
    pulmonary: "Pulmonares",
    chronicDiseases: "Enfermedades crónicas",
    transfusions: "Transfusiones",
    sexuallyTransmittedInfections: "Infecciones de transmisión sexual",
    digestive: "Digestivas",
    surgical: "Quirúrgicas",
    hospitalizations: "Hospitalizaciones",
    others: "Otras",
    other: "Otra",
    specify: "Especificar",
    specifyDesc: "Acá se detalla bien el tipo de antecedente, fecha de diagnóstico o suceso y tratamiento",
    // Non-pathological personal history
    nonPathologicalHistory: "Adulto Antecedentes Personales No Patológicos",
    alcoholism: "Alcoholismo",
    active: "Activo",
    inactive: "Inactivo",
    ageOfOnset: "Edad de inicio",
    ageOfTermination: "Edad de término",
    frequency: "Frecuencia",
    amountOfIntake: "Cantidad de ingesta",
    typeOfLiquor: "Tipo de licor",
    smoking: "Tabaquismo",
    startAge: "Edad de inicio",
    endAge: "Edad de término",
    cigarettesNumber: "Cantidad de cigarrillos o paquetes al día",
    Drogas: "Drugs",
    drugType: "Tipo de droga",
    // Gynecological-obstetric background
    gynecologicalBackground: "Antecedentes Gineco obstétricos",
    menarche: "Menarca",
    sexualLifeBeginning: "Inicio de vida sexual activa",
    sexualPartnersNum: "Número de compañeros sexuales",
    familyPlanning: "Planificación familiar",
    lastMenstrualPeriodDate: "Fecha de última menstruación",
    currentPregnancy: "Embarazo actual",
    weeksOfAmenorrhea: "Semanas de amenorrea",
    estimatedDueDate: "Fecha probable de parto",
    lastDeliveryDate: "Fecha de último parto",
    pregnanciesNumber: "Gestas",
    births: "Partos",
    caesareanSection: "Cesárea",
    abortions: "Abortos",
    curettage: "Legrado",
    // Family Pathological History
    familyPathologicalHistory: "Antecedentes Patológicos Familiares",
    arterialHypertension: "Hipertensión arterial",
    diabetesMellitus: "Diabetes Mellitus",
    tuberculosis: "Tuberculosis",
    cancer: "Cáncer",
    epilepsy: "Epilepsia",
    heartDiseases: "Cardiopatías",
    nephropathies: "Nefropatías",
    liverDiseases: "Hepatopatías",
    mentalDiseases: "Enfermedades mentales",
    familySpecifyDesc: "Acá se detalla bien el tipo de antecedente, fecha de diagnóstico o suceso y grado de consanguinidad del familiar",
    // Socioeconomic situation
    socioeconomicSituation: "Situación socioeconómica",
    house: "Casa",
    own: "Propia",
    rented: "Alquilada",
    walls: "Paredes",
    plastic: "Plástico",
    boards: "Tablas",
    block: "Bloque",
    miniSkirt: "Minifalda",
    zinc: "Zinc",
    flat: "Piso",
    land: "Tierra",
    tiling: "Embaldosado",
    ceramics: "Cerámica",
    ceiling: "Techo",
    roofTile: "Teja",
    bedrooms: "Habitaciones",
    animals: "Animales",
    pet: "Mascota",
    farm: "Granja",
    specifyOnesQuantity: "Especificar cuales y cantidad",
    waterSource: "Fuente de agua",
    well: "Pozo",
    potable: "Potable",
    electricPower: "Energía eléctrica",
    toilet: "Inodoro",
    latrine: "Letrina",
    kitchen: "Cocina",
    gas: "Gas",
    firewood: "Leña",
    population: "Habitantes",
    children_0_5: "Niños (0 a 5 años)",
    children_6_10: "Niños (6 a 10 años)",
    children_11_15: "Niños (11 a 15 años)",
    adults: "Adultos",
    seniors: "Ancianos",
    women: "Mujeres",
    men: "Varones",
    peopleWorkingNumber: "Trabajan",
    // Physical exploration
    physicalExploration: "Exploración Física",
    vitalSigns: "Signos vitales",
    bloodPressure: "Presión Arterial",
    heartRate: "Frecuencia Cardíaca",
    respiratoryRate: "Frecuencia Respiratoria",
    temperature: "Temperatura",
    oxygenSaturation: "Saturación de oxígeno",
    weight: "Peso",
    height: "Talla",
    bodyMassIndex: "Índice de masa muscular",
    consultationReason: "Motivo de Consulta",
    illnessHistory: "Historia de la enfermedad actual",
    objective: "Objetivo",
    head: "Cabeza",
    eyes: "Ojos",
    earsNoseMouth: "ORL",
    neck: "Cuello",
    chest: "Tórax",
    heart: "Corazón",
    lungFields: "Campos Pulmonares",
    abdomen: "Abdomen",
    genitals: "Genitales",
    skeletalMuscle: "Músculo esquelético",
    extremities: "Extremidades",
    neurological: "Neurológico",
    evaluation: "Avalúo",
    plans: "Planes",
    feeding: "Alimentación",
    medicines: "Medicamentos",
    exams: "Exámenes",
    normsOrRecommendations: "Normas o recomendaciones",
    treatingPhysician: "Médico tratante",
    minsaCode: "Código Minsa",
    // EMERGENCY ATTENTION SHEET
    emergencyAttentionSheet: "Hoja De Atención Emergencias",
    emergencyAdmission: "Ingreso a emergencia",
    dayMonthYear: "Día- Mes-Año",
    hour: "Hora",
    medicalRecord: "Nombres",
    names: "Apellidos",
    surnames: "Edad",
    occupation: "Ocupación",
    address: "Dirección",
    phoneNumber: "Número de teléfono",
    id: "Cédula",
    arrivesIn: "Llegó",
    ambulance: "Ambulancia",
    walking: "A pie",
    particular: "Particular",
    buses: "Bus",
    accidentCauses: "Causas de accidente o violencia",
    motorizedVehicle: "Vehículo motorizado",
    naturalPhenomenon: "Fenómeno natural",
    fireExplosion: "Incendio/Explosión",
    drop: "Caída",
    assaultBattery: "Asalto/Agresión",
    lateEffects: "Efectos tardíos",
    machinery: "Maquinaria",
    suicideAttempt: "Intento de suicidio",
    accidentPlace: "Lugar de accidente o violencia",
    work: "Trabajo",
    sportFun: "Deporte/Diversión",
    livingPlace: "Vivienda",
    publicRoad: "Vía Pública",
    studyCenter: "Centro de estudios",
    notifyTo: "En caso de emergencia avisar a",
    name: "Nombre",
    relationship: "Parentesco",
    telephone: "Teléfono",
    breathingFrequency: "Frecuencia respiratoria",
    attentionDateHours: "Hora de atención",
    attendantName: "Nombre de quien atiende",
    personalMedicalHistory: "Antecedentes patológicos personales",
    reasonForConsultation: "Motivo de consulta",
    clinicalSummary: "Resumen Clínico",
    physicalExam: "Examen Físico",
    destiny: "Destino",
    ambulatory: "Alta",
    observation: "Observación",
    ranAway: "Fuga",
    requiredOutput: "Salida exigida",
    abandonment: "Abandono",
    referred: "Referido",
    passAway: "Fallece",
    emergencyType: "Tipo de emergencia",
    medical: "Médica",
    obstetricGynecology: "Gineco obstétrica",
    treatingPhysicianSignature: "Firma, Sello y Código de médico tratante",
    // Postnatal History
    postnatalHistory: "Antecedentes postnatales",
    apgar: "Apgar",
    weightInGrams: "Peso en gramos",
    sizeInCentimeters: "Talla en centímetros",
    suffocation: "Datos de asfixia",
    roomingIn: "Alojamiento Conjunto",
    hospitalization: "Hospitalización (Lugar/Tiempo)",
    // Feeding
    exclusiveBreastfeeding: "Lactancia materna exclusiva",
    durationOfExclusiveBreastfeeding: "Duración de lactancia exclusiva",
    mixedBreastfeeding: "Lactancia mixta",
    mixedBreastfeedingDuration: "Duración de lactancia mixta",
    ablactation: "Ablactación",

    // Inmunizaciones
    immunizations: "Inmunizaciones",
    vaccines: "Vacunas",
    bcg: "BCG",
    pentavalent: "Pentavalente",
    polio: "Polio",
    rotavirus: "Rotavirus",
    mmr: "MMR",
    dpt: "DPT",
    dT: "dT",
    dose1: "1 dosis",
    doses2: "2 dosis",
    doses3: "3 dosis",
    reinforcement: "Refuerzo",
    reinforcementCount: "Refuerzo Dosis",
    doses: "dosis",

    // Psychomotor development
    psychomotorDevelopment: "Desarrollo Psicomotor",
    lessThan1Month: "Menor de 1 mes",
    suckVigorously: "Succiona vigorosamente",
    handsClosed: "Manos cerradas",
    flexArms: "Flexiona brazos y piernas",
    moorishReflex: "Reflejo de moro",
    month1: "1 mes",
    vocalize: "Vocaliza",
    alternateLegMovement: "Alterna movimientos de piernas",
    openHands: "Abre las manos",
    socialSmile: "Sonrisa social",
    months2_3: "2 – 3 meses",
    lookAtMothers: "Mira el rostro de la madre", 
    followObjects: "Sigue objetos con la mirada",
    reactToSound: "Reacciona al sonido",
    raiseHead: "Eleva la cabeza",
    months4_5: "4 – 5 meses",
    answerToExam: "Responde al examen",
    grabObjects: "Agarra objetos",
    makeSounds: "Emite sonidos",
    holdsHead: "Sostiene la cabeza",
    months6_8: "6- 8 meses",
    takeToy: "Intenta tomar un juguete",
    bringsObjectsToMouth: "Lleva objetos a la boca",
    locateSound: "Localiza el sonido",
    turnTowardsObject: "Gira hacia un objeto",
    months9_11: "9 – 11 meses",
    playDiscover: "Juega a descubrirse",
    objectsPassed: "Se pasa objetos",
    sitsAlone: "Se sienta solo",
    doubleSyllables: "Duplica sílabas",
    months12_14: "12 – 14 meses",
    imitateGestures: "Imita gestos",
    topPliers: "Pinzas superiores",
    confusingWords: "Palabras confusas",
    walkWithSupport: "Camina con apoyo",
    months15_17: "15 – 17 meses",
    gesturesOnDemand: "Hace gestos a pedidos",
    placeCubes: "Coloca cubos en recipiente",
    sayWord: "Dice una palabra",
    walkWithoutSupport: "Camina sin apoyo",
    months18_23: "18 – 23 meses",
    identifyTwoObjects: "Identifica dos objetos",
    scribbles: "Hace garabatos",
    saysThreeWords: "Dice tres palabras",
    walkBackwards: "Camina para atrás",
    months24_35: "24 – 35 meses",
    takesOffClothes: "Se quita la rop",
    towerFiveCubes: "Dice frases cortas",
    saysShortSentences: "Patea pelota",
    kickBall: "kick ball",
    months36_59: "36 – 59 meses",
    feedsItself: "Se alimenta solo",
    saysLongSentences: "Dice oraciones largas",
    dressesAlone: "Se viste solo",
    complexOrders: "Órdenes complejas",

    // Pediatric Pathological Personal History
    pediatricPathologicalHistory: "Pediátrica Antecedentes Personales Patológicos",
    infections: "Infecciones",
    surgeries: "Cirugías",

    // Pediatric Physical Exam
    pediatricPhysicalExam: "Pediátrica Examen Físico",
    silvermanAnderson: "Silverman Anderson",
    sizeLength: "Talla/ Longitud",
    anthropometricData: "Datos antropométricos",
    headCircunference: "Perímetro cefálico",
    chestCircumference: "Perímetro torácico",
    abdominalPerimeter: "Perímetro abdominal",
    bodySurfaceArea: "Área de superficie corporal",
    attendsNameSign: "Name and sign of person who attends",

    // SUBSEQUENT EVOLUTION NOTE
    subsequentEvolutionNote: "Nota De Evolución Subsecuente",
    nameSurname: "Edad",
    community: "Comunidad",
    proceedings: "Expediente",
    dateTime: "Fecha y hora",
    size: "Talla",

    // NURSING NOTE
    nursingNote: "Nota De Enfermería",
    note: "Nota",
    nurseName: "Nombre de enfermero",

    // Ultrasound Consultation
    ultrasoundConsultation: "Ultrasound Consultation",
    lastname: "Lastname",
    origin: "Origin",
    ultrasoundPerformed: "Ultrasound performed",
    resource: "Resource",
    date: "date",

    // Laboratory Consultation
    laboratoryConsultation: "Laboratory Consultation",
    testPerformed: "Test performed",

    // Odontology Consultation
    odontologyConsultation: "Odontology Consultation",
    procedurePerformed: "Procedure performed",
    indications: "Indications",

    // Patient Form
    medicalRecordNum: "Número de expediente",
    attentionDateTime: "Fecha de atención",
    resourceThatAttends: "Hora de atención",
    email: "Correo electrónico",
    educationalStatus: "Escolaridad",
    preschool: "Pre escolar",
    primary: "Primaria",
    secondary: "Secundaria",
    university: "Universidad",
    technical: "Técnico",
    knowsReadWrite: "Sabe leer y escribir",
    illiterate: "Analfabeta",

    religion: "Religión",
    catholic: "Católica",
    evangelical: "Evangélica",
    none: "Ninguna",
    maritalStatus: "Estado civil",
    single: "Soltero",
    married: "Casado",
    stableUnion: "Unión estable",
    widower: "Viudo",
    divorced: "Divorciado",

    motherName: "Nombre de madre",
    fatherName: "Nombre de padre",
    birthHistory: "Antecedentes del parto",
    deliveryPlace: "Lugar de atención del parto",
    deliveryDateTime: "Fecha, hora y duración del parto",
    gestationalAge: "Edad gestacional",
    deliveryCare: "Atención del parto",
    nurse: "Enfermero",
    midwife: "Partera",
    via: "Vía",
    vaginal: "Vaginal",
    presentation: "Presentación",
    cephalic: "Cefálica",
    podalic: "Podálica",
    transverse: "Transversa",
    birthingEvents: "Eventualidades del parto",

  }
};